# Generated by Django 4.1.7 on 2023-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0002_alter_item_price_alter_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
